Stop using argparse.MetavarTypeHelpFormatter
MetavarTypeHelpFormatter doesn't exist in Python 3.2, and all our
metavars are overridden anyway.

Fixes:

    AttributeError: 'module' object has no attribute 'MetavarTypeHelpFormatter'