Try more terminal reset codes when sgr0 isn't available
When the TERM variable is set to dumb, sgr0 isn't available.

Reset all colours (oc) when it isn't available or
just the foreground/background (op) as appropriate.
Ignore terminal attributes when resets are unavailable.

Reported-by: Trent W. Buck (twb)
Reported-in: #debian-mentors

Traceback (most recent call last):
  File "check-all-the-things", line 1125, in <module>
    main()
  File "check-all-the-things", line 1084, in main
    output = check.do(name, jobs, types, run, hide, limit, method, terminal, remarks)
  File "check-all-the-things", line 605, in do
    output, trimmed = spawn(terminal, method, cmd, hide, header, footer, limit)
  File "check-all-the-things", line 287, in spawn
    return spawn_ptyprocess(terminal, cmd, hide, header, footer, limit)
  File "check-all-the-things", line 182, in spawn_ptyprocess
    sys.stdout.buffer.write(reset_term)
TypeError: a bytes-like object is required, not 'NoneType'