Do not enable terminal mode if new pty devices are not available
Both of the terminal-based spawn modes expect to create new pty devices.

This can happen in manually setup chroots on Linux without a proper
setup for the /dev/pts or /dev directories, including with a static /dev
or where the devpts filesystem isn't mounted correctly.

Reported-by: Trent W. Buck (twb)
Reported-in: #debian-mentors

Traceback (most recent call last):
  File "check-all-the-things", line 1125, in <module>
    main()
  File "check-all-the-things", line 1084, in main
    output = check.do(name, jobs, types, run, hide, limit, method, terminal, remarks)
  File "check-all-the-things", line 605, in do
    output, trimmed = spawn(terminal, method, cmd, hide, header, footer, limit)
  File "check-all-the-things", line 290, in spawn
    return spawn_pty(terminal, cmd, hide, header, footer, limit)
  File "check-all-the-things", line 220, in spawn_pty
    pty.spawn(['sh', '-c', cmd], read)
  File "/usr/lib/python3.5/pty.py", line 154, in spawn
    pid, master_fd = fork()
  File "/usr/lib/python3.5/pty.py", line 96, in fork
    master_fd, slave_fd = openpty()
  File "/usr/lib/python3.5/pty.py", line 29, in openpty
    master_fd, slave_name = _open_terminal()
  File "/usr/lib/python3.5/pty.py", line 59, in _open_terminal
    raise OSError('out of pty devices')
OSError: out of pty devices

Traceback (most recent call last):
  File "check-all-the-things", line 1125, in <module>
    main()
  File "check-all-the-things", line 1084, in main
    output = check.do(name, jobs, types, run, hide, limit, method, terminal, remarks)
  File "check-all-the-things", line 605, in do
    output, trimmed = spawn(terminal, method, cmd, hide, header, footer, limit)
  File "check-all-the-things", line 287, in spawn
    return spawn_ptyprocess(terminal, cmd, hide, header, footer, limit)
  File "check-all-the-things", line 158, in spawn_ptyprocess
    proc = ptyprocess.ptyprocess.PtyProcess.spawn(['sh', '-c', cmd])
  File "/usr/lib/python3/dist-packages/ptyprocess/ptyprocess.py", line 220, in spawn
    pid, fd = pty.fork()
  File "/usr/lib/python3.5/pty.py", line 96, in fork
    master_fd, slave_fd = openpty()
  File "/usr/lib/python3.5/pty.py", line 29, in openpty
    master_fd, slave_name = _open_terminal()
  File "/usr/lib/python3.5/pty.py", line 59, in _open_terminal
    raise OSError('out of pty devices')
OSError: out of pty devices