Improve wrapping of the remarks section wrt terminals
Default to 80 columns on terminals instead of 70.

Do not do any wrapping when not on a terminal.

Reported-by: Trent W. Buck (twb)
Reported-in: #debian-au

Traceback (most recent call last):
  File "check-all-the-things", line 1112, in <module>
    main()
  File "check-all-the-things", line 1107, in main
    print(out.fill(' '.join(sorted(remarks[reason]))))
  File "/usr/lib/python3.5/textwrap.py", line 363, in fill
    return "\n".join(self.wrap(text))
  File "/usr/lib/python3.5/textwrap.py", line 354, in wrap
    return self._wrap_chunks(chunks)
  File "/usr/lib/python3.5/textwrap.py", line 248, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width 0 (must be > 0)